# Generated by Django 6.0 on 2026-01-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('memes', 'Меми'), ('pupils', 'Учні'), ('other', 'Інше')], default='memes', max_length=20),
        ),
    ]
